# fly.toml app configuration file generated for nginx-rtmp-flyio on 2025-04-23T12:19:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tvrelay"  # შეცვალე შენი Fly.io აპის სახელით

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  internal_port = 1935
  protocol = "tcp"
  [[services.ports]]
    port = 1935

[http_service]
  internal_port = 1935
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
