app = "tvrelay"  # შეცვალე შენი Fly.io აპის სახელით

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  internal_port = 1935
  protocol = "tcp"
  [[services.ports]]
    port = 1935
